name: apats-sim
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - appdirs=1.4.3=py_1
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - black=19.10b0=py38_0
  - bleach=3.1.4=pyh9f0ad1d_0
  - boost-cpp=1.72.0=h8e57a91_0
  - brotlipy=0.7.0=py38h1e0a361_1000
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cairo=1.16.0=hcf35c78_1003
  - cartopy=0.17.0=py38h9cf8511_1015
  - certifi=2020.4.5.1=py38h32f6830_0
  - cffi=1.14.0=py38hd463f26_0
  - cfitsio=3.470=h00dd3da_3
  - chardet=3.0.4=py38h32f6830_1006
  - click=7.1.1=pyh8c360ce_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - cloudpickle=1.3.0=py_0
  - cryptography=2.8=py38h766eaa4_2
  - curl=7.69.1=h33f0ec9_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py38h516909a_0
  - dask-core=2.15.0=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38h32f6830_1001
  - expat=2.2.9=he1b5a44_2
  - fiona=1.8.13=py38h900e953_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.1=he06d7ca_0
  - freexl=1.0.5=h14c3975_1002
  - gdal=3.0.4=py38h172510d_8
  - geopandas=0.7.0=py_1
  - geos=3.8.1=he1b5a44_0
  - geotiff=1.5.1=h05acad5_10
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_2
  - glib=2.64.2=h6f030ca_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.6=nompi_h3c11f04_100
  - icu=64.2=he1b5a44_1
  - idna=2.9=py_1
  - imageio=2.8.0=py_0
  - importlib-metadata=1.6.0=py38h32f6830_0
  - importlib_metadata=1.6.0=0
  - ipykernel=5.2.1=py38h23f93f0_0
  - ipython=7.13.0=py38h32f6830_2
  - ipython_genutils=0.2.0=py_1
  - jedi=0.17.0=py38h32f6830_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h14c3975_1001
  - jsonschema=3.2.0=py38h32f6830_1
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py38h32f6830_1
  - kealib=1.4.13=h33137a7_1
  - kiwisolver=1.2.0=py38hbf85e49_0
  - krb5=1.17.1=h2fd8d38_0
  - ld_impl_linux-64=2.34=h53a641e_0
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libclang=9.0.1=default_hde54327_0
  - libcurl=7.69.1=hf7181ac_0
  - libdap4=3.20.6=h1d1bd15_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgdal=3.0.4=h99f9e9c_8
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libiconv=1.15=h516909a_1006
  - libkml=1.3.0=hb574062_1011
  - liblapack=3.8.0=16_openblas
  - libllvm9=9.0.1=he513fc3_1
  - libnetcdf=4.7.4=nompi_h84807e1_103
  - libopenblas=0.3.9=h5ec1e0e_0
  - libpng=1.6.37=hed695b0_1
  - libpq=12.2=h5513abc_1
  - libsodium=1.0.17=h516909a_0
  - libspatialindex=1.9.3=he1b5a44_3
  - libspatialite=4.3.0a=h2482549_1038
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - libxslt=1.1.33=h31b3aaa_0
  - llvm-openmp=10.0.0=hc9558a2_0
  - lxml=4.5.0=py38hbb43d70_1
  - lz4-c=1.9.2=he1b5a44_0
  - markupsafe=1.1.1=py38h1e0a361_1
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py38h2af1d28_0
  - metpy=0.12.1=py_0
  - mistune=0.8.4=py38h1e0a361_1001
  - munch=2.5.0=py_0
  - mypy_extensions=0.4.3=py38h32f6830_1
  - nbconvert=5.6.1=py38h32f6830_1
  - nbformat=5.0.6=py_0
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.4=py_1
  - notebook=6.0.3=py38_0
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.18.1=py38h8854b6b_1
  - olefile=0.46=py_0
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1g=h516909a_0
  - owslib=0.19.2=py_1
  - packaging=20.1=py_0
  - pandas=1.0.3=py38hcb8c335_1
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.0=pyh9f0ad1d_0
  - pathspec=0.8.0=pyh9f0ad1d_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py38h32f6830_1
  - pickleshare=0.7.5=py38h32f6830_1001
  - pillow=7.1.2=py38h9776b28_0
  - pint=0.11=py_1
  - pip=20.0.2=py_2
  - pixman=0.38.0=h516909a_1003
  - pooch=1.1.0=py_0
  - poppler=0.87.0=h4190859_1
  - poppler-data=0.4.9=1
  - postgresql=12.2=h8573dbc_1
  - proj=7.0.0=h966b41f_3
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.5=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=py_0
  - pyepsg=0.4.0=py_0
  - pygments=2.6.1=py_0
  - pykdtree=1.3.1=py38h8790de6_1003
  - pykrige=1.5.0=py38h1e0a361_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.6.0=py38h7521cb9_1
  - pyqt=5.12.3=py38hcca6a23_1
  - pyrsistent=0.16.0=py38h1e0a361_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py38h32f6830_1
  - python=3.8.2=he5300dc_7_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py38h8790de6_1
  - pyyaml=5.3.1=py38h1e0a361_0
  - pyzmq=19.0.0=py38ha71036d_1
  - qt=5.12.5=hd8c4c69_1
  - readline=8.0=hf8c457e_0
  - regex=2020.4.4=py38h1e0a361_0
  - requests=2.23.0=pyh8c360ce_2
  - rtree=0.9.4=py38h08f867b_1
  - scikit-image=0.16.2=py38hb3f55d8_0
  - scikit-learn=0.22.2.post1=py38hcdab131_0
  - scipy=1.4.1=py38h18bccfc_3
  - send2trash=1.5.0=py_0
  - setuptools=46.1.3=py38h32f6830_0
  - shapely=1.7.0=py38hd168ffb_3
  - six=1.14.0=py_1
  - sqlite=3.30.1=hcee41ef_0
  - tbb=2018.0.5=h2d50403_0
  - terminado=0.8.3=py38h32f6830_1
  - testpath=0.4.4=py_0
  - tiledb=1.7.7=h8efa9f0_1
  - tk=8.6.10=hed695b0_0
  - toml=0.10.0=py_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py38h1e0a361_1
  - traitlets=4.3.3=py38h32f6830_1
  - typed-ast=1.4.1=py38h516909a_0
  - typing_extensions=3.7.4.2=py_0
  - tzcode=2020a=h516909a_0
  - urllib3=1.25.9=py_0
  - wcwidth=0.1.9=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - xarray=0.15.1=py_0
  - xerces-c=3.2.2=h8412b87_1004
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_0
  - yaml=0.2.4=h516909a_0
  - zeromq=4.3.2=he1b5a44_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zope.event=4.4=py38_0
  - zstd=1.4.4=h6597ccf_3
  - pip:
    - naturalneighbor==0.2.1
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: /home/ubuntu/miniconda3/envs/apats-sim

